@server=http://localhost:4004
@username=alice
@password=


### teach
# @name teach_GET
GET {{server}}/odata/v4/edex-tech-api/teach
Authorization: Basic {{username}}:{{password}}


### teach
# @name teach_POST
POST {{server}}/odata/v4/edex-tech-api/teach
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "teach-1643524",
  "Name": "Name-1643524",
  "Contact": "Install package 'randexp' to create data for regex ^[0-9]{10}$",
  "Email": "Install package 'randexp' to create data for regex ^.+@.+$",
  "Salary": "Salary-1643524",
  "Address": "Address-1643524",
  "createdAt": "2010-10-08T00:00:00.000Z",
  "createdBy": "createdBy.z85g@example.org",
  "modifiedAt": "2012-11-02T00:00:00.000Z",
  "modifiedBy": "modifiedBy.z85g@example.com",
  "validFrom": "2009-10-08T00:00:00.000Z",
  "validTo": "2004-06-13T00:00:00.000Z"
}


### teach
# @name teach_PATCH
PATCH {{server}}/odata/v4/edex-tech-api/teach/teach-1643524
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "teach-1643524",
  "Name": "Name-1643524",
  "Contact": "Install package 'randexp' to create data for regex ^[0-9]{10}$",
  "Email": "Install package 'randexp' to create data for regex ^.+@.+$",
  "Salary": "Salary-1643524",
  "Address": "Address-1643524",
  "createdAt": "2010-10-08T00:00:00.000Z",
  "createdBy": "createdBy.z85g@example.org",
  "modifiedAt": "2012-11-02T00:00:00.000Z",
  "modifiedBy": "modifiedBy.z85g@example.com",
  "validFrom": "2009-10-08T00:00:00.000Z",
  "validTo": "2004-06-13T00:00:00.000Z"
}


### teach
# @name teach_DELETE
DELETE {{server}}/odata/v4/edex-tech-api/teach/teach-1643524
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### edexTech
# @name edexTech_GET
GET {{server}}/odata/v4/edex-tech-api/edexTech
Authorization: Basic {{username}}:{{password}}


### edexTech
# @name edexTech_POST
POST {{server}}/odata/v4/edex-tech-api/edexTech
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "TeachID": {
    "ID": "teach-1643524"
  },
  "StudID": {
    "ID": "1472030a-5815-4e14-a14b-220db5200fca"
  }
}


### edexTech
# @name edexTech_PATCH
PATCH {{server}}/odata/v4/edex-tech-api/edexTech(TeachID=[object Object],StudID=[object Object])
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "TeachID": {
    "ID": "teach-1643524"
  },
  "StudID": {
    "ID": "1472030a-5815-4e14-a14b-220db5200fca"
  }
}


### edexTech
# @name edexTech_DELETE
DELETE {{server}}/odata/v4/edex-tech-api/edexTech(TeachID=[object Object],StudID=[object Object])
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### stud
# @name stud_GET
GET {{server}}/odata/v4/edex-tech-api/stud
Authorization: Basic {{username}}:{{password}}


### stud
# @name stud_POST
POST {{server}}/odata/v4/edex-tech-api/stud
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "1472030a-5815-4e14-a14b-220db5200fca",
  "Name": "Name-1472030",
  "Phone": "Phone-1472030",
  "Email": "Email-1472030",
  "Fees": "Fees-1472030",
  "Address": {
    "Street": "Street-1472030",
    "City": "City-1472030",
    "Pincode": "Pincode-1472030"
  }
}


### stud
# @name stud_PATCH
PATCH {{server}}/odata/v4/edex-tech-api/stud/1472030a-5815-4e14-a14b-220db5200fca
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "1472030a-5815-4e14-a14b-220db5200fca",
  "Name": "Name-1472030",
  "Phone": "Phone-1472030",
  "Email": "Email-1472030",
  "Fees": "Fees-1472030",
  "Address": {
    "Street": "Street-1472030",
    "City": "City-1472030",
    "Pincode": "Pincode-1472030"
  }
}


### stud
# @name stud_DELETE
DELETE {{server}}/odata/v4/edex-tech-api/stud/1472030a-5815-4e14-a14b-220db5200fca
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### order
# @name order_GET
GET {{server}}/odata/v4/edex-tech-api/order
Authorization: Basic {{username}}:{{password}}


### order
# @name order_POST
POST {{server}}/odata/v4/edex-tech-api/order
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "order-671311",
  "Name": "Name-671311",
  "OrderDate": 54,
  "Place": "Place-671311",
  "Status": "Status-671311",
  "location": {
    "City": "City-671311",
    "Pincode": "Pincode-671311"
  }
}


### order
# @name order_PATCH
PATCH {{server}}/odata/v4/edex-tech-api/order/order-671311
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "order-671311",
  "Name": "Name-671311",
  "OrderDate": 54,
  "Place": "Place-671311",
  "Status": "Status-671311",
  "location": {
    "City": "City-671311",
    "Pincode": "Pincode-671311"
  }
}


### order
# @name order_DELETE
DELETE {{server}}/odata/v4/edex-tech-api/order/order-671311
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### updateSalary
# @name updateSalary_POST
POST {{server}}/odata/v4/edex-tech-api/updateSalary
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "ID-21895756",
  "Salary": "Salary-21895756"
}


### updateStatus
# @name updateStatus_POST
POST {{server}}/odata/v4/edex-tech-api/updateStatus
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "O11",
  "Status": "Approved"
}
